// Generated by scripts/generate_ts_client.py from schemas/v1. Do not edit.
// Regenerate with: python3 scripts/generate_ts_client.py

import type {
  AgentOutputVerificationResponse,
  AgenticInteractionTrustRequest,
  AgenticInteractionTrustResponse,
  CISSecondarySanctionsExposureRequest,
  CISSecondarySanctionsExposureResponse,
  CriticalMineralsDueDiligenceRequest,
  CriticalMineralsDueDiligenceResponse,
  GulfMaritimeExposureRequest,
  GulfMaritimeExposureResponse,
  MarketEntryReadinessRequest,
  MarketEntryReadinessResponse,
  MiddleCorridorDealRiskRequest,
  MiddleCorridorDealRiskResponse,
  PreActionCheckRequest,
  PreActionCheckResponse,
} from "./types.js";

export type JsonObject = Record<string, unknown>;

export interface ClientOptions {
  /** Base URL of the Agenda Intelligence HTTP shell, without a trailing slash. */
  baseUrl: string;
  /** Bearer secret issued by the operator. Omit only against an open dev instance. */
  apiKey?: string;
  /** Milliseconds before a call is abandoned. Default 30000. */
  timeoutMs?: number;
  /** Injected for tests and for runtimes without a global fetch. */
  fetch?: typeof fetch;
}

export interface CallOptions {
  /** Correlation id echoed back on the response and in the operator's logs. */
  requestId?: string;
  signal?: AbortSignal;
}

/** Any non-2xx answer. `body` is the shell's JSON error when it sent one. */
export class AgendaIntelligenceError extends Error {
  readonly status: number;
  readonly requestId: string | null;
  readonly body: JsonObject | null;

  constructor(message: string, status: number, requestId: string | null, body: JsonObject | null) {
    super(message);
    this.name = "AgendaIntelligenceError";
    this.status = status;
    this.requestId = requestId;
    this.body = body;
  }
}

/** 429. Wait `retryAfterSeconds` before the next call rather than retrying at once. */
export class RateLimitError extends AgendaIntelligenceError {
  readonly retryAfterSeconds: number;
  readonly limitPerMinute: number | null;

  constructor(
    message: string,
    requestId: string | null,
    body: JsonObject | null,
    retryAfterSeconds: number,
    limitPerMinute: number | null,
  ) {
    super(message, 429, requestId, body);
    this.name = "RateLimitError";
    this.retryAfterSeconds = retryAfterSeconds;
    this.limitPerMinute = limitPerMinute;
  }
}

export class AgendaIntelligenceClient {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly timeoutMs: number;
  private readonly fetchImpl: typeof fetch;

  constructor(options: ClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.apiKey = options.apiKey;
    this.timeoutMs = options.timeoutMs ?? 30000;
    if (!Number.isFinite(this.timeoutMs) || this.timeoutMs <= 0) throw new Error("timeoutMs must be positive");
    const impl = options.fetch ?? globalThis.fetch;
    if (!impl) {
      throw new Error("No fetch available; pass one in ClientOptions.fetch");
    }
    this.fetchImpl = impl;
  }

  /** Liveness. Answers without a key, so it distinguishes 'starting' from 'broken'. */
  health(options?: CallOptions): Promise<JsonObject> {
    return this.get<JsonObject>("/healthz", options);
  }

  /** Readiness, including the access policy this instance is enforcing. */
  ready(options?: CallOptions): Promise<JsonObject> {
    return this.get<JsonObject>("/readyz", options);
  }

  /** Audit claim/evidence references in an audit packet. */
  auditClaims(request: JsonObject, options?: CallOptions): Promise<JsonObject> {
    return this.post<JsonObject>("/v1/audit-claims", request, options);
  }
  /** Report source coverage for an evidence pack. */
  sourceCoverage(request: JsonObject, options?: CallOptions): Promise<JsonObject> {
    return this.post<JsonObject>("/v1/source-coverage", request, options);
  }
  /** Score a rewrite against the memo-quality rubric. */
  score(request: JsonObject, options?: CallOptions): Promise<JsonObject> {
    return this.post<JsonObject>("/v1/score", request, options);
  }
  /** Middle Corridor deal-risk triage. */
  middleCorridorDealRisk(request: MiddleCorridorDealRiskRequest, options?: CallOptions): Promise<MiddleCorridorDealRiskResponse> {
    return this.post<MiddleCorridorDealRiskResponse>("/v1/middle-corridor/deal-risk", request, options);
  }
  /** Agentic interaction evidence triage. */
  agenticInteractionTrust(request: AgenticInteractionTrustRequest, options?: CallOptions): Promise<AgenticInteractionTrustResponse> {
    return this.post<AgenticInteractionTrustResponse>("/v1/agentic-interaction/trust", request, options);
  }
  /** CIS secondary-sanctions exposure triage. */
  cisSecondarySanctionsExposure(request: CISSecondarySanctionsExposureRequest, options?: CallOptions): Promise<CISSecondarySanctionsExposureResponse> {
    return this.post<CISSecondarySanctionsExposureResponse>("/v1/cis-secondary-sanctions/exposure", request, options);
  }
  /** Gulf maritime exposure triage. */
  gulfMaritimeExposure(request: GulfMaritimeExposureRequest, options?: CallOptions): Promise<GulfMaritimeExposureResponse> {
    return this.post<GulfMaritimeExposureResponse>("/v1/gulf-maritime/exposure", request, options);
  }
  /** Market-entry evidence-readiness triage. */
  marketEntryReadiness(request: MarketEntryReadinessRequest, options?: CallOptions): Promise<MarketEntryReadinessResponse> {
    return this.post<MarketEntryReadinessResponse>("/v1/market-entry/readiness", request, options);
  }
  /** Critical-minerals due-diligence triage. */
  criticalMineralsDueDiligence(request: CriticalMineralsDueDiligenceRequest, options?: CallOptions): Promise<CriticalMineralsDueDiligenceResponse> {
    return this.post<CriticalMineralsDueDiligenceResponse>("/v1/critical-minerals/due-diligence", request, options);
  }
  /** Verify an agent-output evidence packet and return repair guidance. */
  agentOutputVerification(request: JsonObject, options?: CallOptions): Promise<AgentOutputVerificationResponse> {
    return this.post<AgentOutputVerificationResponse>("/v1/agent-output/verification", request, options);
  }
  /** Deterministic pre-action routing over claims and evidence. */
  preActionCheck(request: PreActionCheckRequest, options?: CallOptions): Promise<PreActionCheckResponse> {
    return this.post<PreActionCheckResponse>("/v1/agent-output/pre-action-check", request, options);
  }

  private get<T>(path: string, options?: CallOptions): Promise<T> {
    return this.request<T>("GET", path, undefined, options);
  }

  private post<T>(path: string, body: unknown, options?: CallOptions): Promise<T> {
    return this.request<T>("POST", path, body, options);
  }

  private async request<T>(method: string, path: string, body: unknown, options?: CallOptions): Promise<T> {
    const headers: Record<string, string> = { accept: "application/json" };
    if (this.apiKey) headers.authorization = `Bearer ${this.apiKey}`;
    if (options?.requestId) headers["x-request-id"] = options.requestId;
    if (body !== undefined) headers["content-type"] = "application/json";

    if (options?.signal?.aborted) throw new DOMException("Call was aborted", "AbortError");
    const serialized = body === undefined ? undefined : JSON.stringify(body);
    const controller = new AbortController();
    const abort = () => controller.abort();
    const timer = setTimeout(abort, this.timeoutMs);
    options?.signal?.addEventListener("abort", abort, { once: true });
    try {
      const init: RequestInit = { method, headers, signal: controller.signal };
      if (serialized !== undefined) init.body = serialized;
      const response = await this.fetchImpl(this.baseUrl + path, init);
      const requestId = response.headers.get("x-request-id");
      const text = await response.text();
      let parsed: unknown = null;
      try { parsed = JSON.parse(text); } catch { /* Keep HTTP failure status even without JSON. */ }
      const payload = parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as JsonObject : null;
      if (response.status === 429) {
        const header = Number(response.headers.get("retry-after"));
        const fromBody = typeof payload?.retry_after_seconds === "number" ? payload.retry_after_seconds : null;
        const limit = typeof payload?.limit_per_minute === "number" ? payload.limit_per_minute : null;
        const retry = Number.isFinite(header) && header > 0 ? header :
          fromBody !== null && Number.isFinite(fromBody) && fromBody > 0 ? fromBody : 60;
        throw new RateLimitError("Rate limit exceeded", requestId, payload, retry, limit);
      }
      if (!response.ok) {
        const message = typeof payload?.error === "string" ? payload.error : `Request failed with ${response.status}`;
        throw new AgendaIntelligenceError(message, response.status, requestId, payload);
      }
      if (!payload) {
        throw new AgendaIntelligenceError("Response was not a JSON object", response.status, requestId, null);
      }
      return payload as T;
    } finally {
      clearTimeout(timer);
      options?.signal?.removeEventListener("abort", abort);
    }
  }
}
