// Generated by scripts/generate_ts_client.py from schemas/v1. Do not edit.
// Regenerate with: python3 scripts/generate_ts_client.py

/** Structured verdict for whether one agent's claim-backed output is ready for a consuming agent to relay or act on. Wraps a claim-level evidence audit (evidence-audit.schema.json) and returns a machine-actionable relay verdict, weak/unsafe claim triage, evidence gaps, and owner actions. Schema-level and structural only: it does not verify that any claim or quote is factually true, does not fetch or validate cited sources, and does not authorize an action or provide legal, compliance, sanctions, financial, or investment advice. */
export interface AgentOutputVerificationResponse {
  /** Machine-actionable relay verdict. allow_relay: every claim is grounded and none is unsupported. verify_before_relay: claims are declared-supported but carry weak support or span-grounding gaps. block_unsafe_claims: at least one claim is marked unsupported or cites evidence that is not present. not_decision_ready / insufficient_information: not enough structured claim material to verdict, or no claim cites evidence present in the supplied pack. A declared support_level is a caller assertion, not a verified fact: it counts only where the claim cites an evidence_id the caller actually supplied. */
  verdict: "allow_relay" | "verify_before_relay" | "block_unsafe_claims" | "not_decision_ready" | "insufficient_information";
  trust_signal: "low" | "medium" | "medium_high" | "high" | "unknown";
  /** Heuristic 0-100 score for how ready the supplied claim set is for relay. Only claims that cite an evidence_id present in the supplied evidence contribute to it; a claim whose declared support_level nothing in the pack corroborates weighs nothing, and any such claim holds the score below the review_ready band. Not approval, clearance, or factual verification. */
  readiness_score: number;
  readiness_label: "insufficient_information" | "not_decision_ready" | "partial" | "review_ready";
  claim_count: number;
  /** Number of claims that carry at least one supporting quote span. */
  grounded_claim_count: number;
  /** Claims that must not be relayed as fact: marked unsupported, or citing evidence_ids absent from the supplied evidence. */
  unsafe_claims: Array<{
    claim_id: string;
    claim?: string;
    reason: string;
  }>;
  /** Claims declared with weak support that should be strengthened before relay. */
  weak_claims: Array<{
    claim_id: string;
    claim?: string;
  }>;
  /** Statements the producing agent itself flagged as unsupported (from evidence-audit unsupported_claims). */
  unsupported_statements: string[];
  evidence_gaps: string[];
  /** Concrete fixes the producing agent should make before the output is relayed. */
  owner_actions: string[];
  watch_next: string[];
  /** True for any verdict other than allow_relay: a human should review before the consuming agent acts. */
  human_review_required: boolean;
  not_advice_notice: string;
  limitations: string[];
}

export interface AgenticInteractionTrustRequestActor {
  declared_type: "ai_agent" | "automation_script" | "api_client" | "browser_bot" | "human_delegated_agent" | "unknown" | "other";
  declared_name: string;
  /** Declared operator, principal, organization, or user on whose behalf the actor claims to act. */
  operator?: string;
  declared_agent_id?: string;
  declared_user_agent?: string;
  authentication_context?: "anonymous" | "session_cookie" | "api_key" | "oauth" | "mTLS" | "signed_agent_manifest" | "unknown" | "other";
}

export type AgenticInteractionTrustRequestTargetSurface = "checkout" | "account" | "api" | "mcp_tool" | "a2a_endpoint" | "content_or_catalog" | "auth_flow" | "support_or_messaging" | "other";

export interface AgenticInteractionTrustRequestDatedSource {
  id: string;
  source_type: AgenticInteractionTrustRequestSourceType;
  title: string;
  date: string;
  url?: string;
  notes?: string;
}

export type AgenticInteractionTrustRequestSourceType = "agent_identity_claim" | "operator_or_principal_authorization" | "agent_card_or_manifest" | "mcp_or_a2a_endpoint_metadata" | "tool_scope_or_permission_evidence" | "session_authentication_evidence" | "action_intent_evidence" | "transaction_or_target_action_evidence" | "rate_limit_or_abuse_signal" | "fraud_or_account_takeover_signal" | "device_or_infrastructure_evidence" | "provider_policy_or_allowlist" | "prior_interaction_history" | "incident_report_or_threat_intel" | "human_review_note" | "user_provided_note" | "other";

/** Product-grade structured request contract for evidence triage of agent-mediated interactions across checkout, account, API, MCP tool, and A2A endpoint surfaces. The contract asks whether the supplied evidence is sufficient for allow, step-up, human-review, or block-until-verified routing. It does not provide cybersecurity monitoring, fraud adjudication, legal advice, compliance advice, financial advice, identity verification, transaction authorization, autonomous blocking, live retrieval, or factual-truth verification. */
export interface AgenticInteractionTrustRequest {
  actor: AgenticInteractionTrustRequestActor;
  target_surface: AgenticInteractionTrustRequestTargetSurface;
  /** The concrete action the agent, automated client, or delegated actor is trying to perform. */
  requested_action: string;
  /** Optional account, endpoint, order, transaction, MCP tool, A2A capability, or other resource under review. */
  asset_or_resource?: string;
  decision_stage: "pre_execution" | "in_session" | "post_alert" | "policy_review" | "committee_review" | "other";
  dated_sources: AgenticInteractionTrustRequestDatedSource[];
  risk_question: string;
  notes?: string;
  requested_output?: "structured_json" | "markdown_summary" | "both";
}

export type AgenticInteractionTrustResponseTargetSurface = "checkout" | "account" | "api" | "mcp_tool" | "a2a_endpoint" | "content_or_catalog" | "auth_flow" | "support_or_messaging" | "other";

export type AgenticInteractionTrustResponseSourceType = "agent_identity_claim" | "operator_or_principal_authorization" | "agent_card_or_manifest" | "mcp_or_a2a_endpoint_metadata" | "tool_scope_or_permission_evidence" | "session_authentication_evidence" | "action_intent_evidence" | "transaction_or_target_action_evidence" | "rate_limit_or_abuse_signal" | "fraud_or_account_takeover_signal" | "device_or_infrastructure_evidence" | "provider_policy_or_allowlist" | "prior_interaction_history" | "incident_report_or_threat_intel" | "human_review_note" | "user_provided_note" | "other";

export interface AgenticInteractionTrustResponseReadinessNamedValue {
  field: string;
  value: string;
}

/** Additive normalized readiness view for cross-profile human-review routing. Built from existing response fields; does not replace profile-specific fields and does not imply approval, clearance, advice, factual verification, or autonomous decision-making. */
export interface AgenticInteractionTrustResponseReadinessContract {
  profile: string;
  status: string;
  score: number | null;
  routing: AgenticInteractionTrustResponseReadinessNamedValue | null;
  signal: AgenticInteractionTrustResponseReadinessNamedValue | null;
  blocking_gaps: unknown[];
  non_blocking_gaps: unknown[];
  claim_audit: unknown[];
  owner_actions: unknown[];
  watch_next: string[];
  human_review_required: boolean;
  boundary_notice: string;
}

/** Product-grade structured response contract for evidence triage of agent-mediated interactions. Supports trust-signal routing, evidence gaps, source coverage, watch-next indicators, and human-review requirements. It does not provide cybersecurity monitoring, fraud adjudication, legal advice, compliance advice, financial advice, identity verification, transaction authorization, autonomous blocking, live retrieval, or factual-truth verification. */
export interface AgenticInteractionTrustResponse {
  triage_recommendation: "allow_low_risk" | "require_step_up" | "escalate_to_human_review" | "block_until_verified" | "not_decision_ready" | "insufficient_information";
  trust_signal: "low" | "medium" | "medium_high" | "high" | "unknown";
  /** Heuristic 0-100 score for evidence-pack readiness for a human trust-routing decision. This is not approval, clearance, fraud adjudication, cybersecurity monitoring, identity verification, legal advice, compliance advice, financial advice, or transaction authorization. */
  decision_readiness_score: number;
  decision_readiness_label: "insufficient_information" | "not_decision_ready" | "partial" | "review_ready";
  actor?: {
    [key: string]: unknown;
  };
  target_surface: AgenticInteractionTrustResponseTargetSurface;
  requested_action: string;
  asset_or_resource?: string;
  supplied_sources: AgenticInteractionTrustResponseSourceType[];
  minimum_sources_before_action: AgenticInteractionTrustResponseSourceType[];
  evidence_gaps: string[];
  top_risk_dimensions?: string[];
  watch_next: string[];
  human_review_required: boolean;
  not_advice_notice: string;
  limitations?: string[];
  readiness_contract?: AgenticInteractionTrustResponseReadinessContract;
}

export interface CISSecondarySanctionsExposureRequestCounterparty {
  name: string;
  /** Primary CIS jurisdiction of the counterparty (e.g., Kazakhstan, Uzbekistan, Georgia). */
  jurisdiction: string;
  sector?: "trading_house" | "logistics_forwarder" | "bank" | "fintech" | "broker_dealer" | "manufacturer" | "ict_or_electronics" | "metals_or_mining" | "energy_or_petrochem" | "agribusiness_or_grain" | "construction" | "professional_services" | "holding_or_spv" | "unknown" | "other";
  /** Free-text ordered chain of disclosed ownership layers, from immediate parent to ultimate beneficial owner where known. */
  ownership_layers?: string[];
  registered_identifiers?: Array<{
    scheme: "lei" | "national_bin" | "national_tin" | "isin" | "other";
    value: string;
  }>;
  notes?: string;
}

export type CISSecondarySanctionsExposureRequestExposureFacet = "ownership_or_control" | "financial_flows" | "ict_or_dual_use_goods" | "metals_or_mining" | "energy_or_petrochem" | "agribusiness_or_grain" | "transit_or_re_export" | "correspondent_banking" | "professional_enablers" | "shell_or_layered_structure" | "other";

export interface CISSecondarySanctionsExposureRequestDatedSource {
  id: string;
  source_type: CISSecondarySanctionsExposureRequestSourceType;
  title: string;
  date: string;
  url?: string;
  notes?: string;
}

export type CISSecondarySanctionsExposureRequestSourceType = "ofac_sdn_extract" | "eu_consolidated_extract" | "uk_ofsi_extract" | "un_security_council_extract" | "ownership_chain_evidence" | "beneficial_ownership_source" | "bank_correspondent_evidence" | "transit_or_invoice_evidence" | "dual_use_export_evidence" | "customs_data_evidence" | "adverse_media_evidence" | "typology_reference" | "national_regulator_filing" | "user_provided_note" | "other";

/** Product-grade structured request contract for secondary-sanctions exposure evidence triage of a CIS, Caucasus, or Central Asia counterparty (Kazakhstan, Uzbekistan, Kyrgyzstan, Tajikistan, Turkmenistan, Georgia, Armenia, Azerbaijan, Moldova). Designed for enhanced due diligence in EU / UK / UAE / Singapore institutions screening counterparties against OFAC EO 14114, EU sanctions package, UK OFSI, and FATF / EAG typologies for Russia-related re-export and circumvention risk. This schema describes caller-supplied counterparty, ownership, financial-flow, transit, and dated-source inputs. It does not enable live retrieval, factual-truth verification, legal advice, sanctions advice, compliance advice, financial advice, investment advice, insurance advice, or trading advice. */
export interface CISSecondarySanctionsExposureRequest {
  counterparty: CISSecondarySanctionsExposureRequestCounterparty;
  exposure_facets: CISSecondarySanctionsExposureRequestExposureFacet[];
  jurisdiction_review_scope?: Array<"ofac" | "eu" | "uk_ofsi" | "un" | "fatf" | "eag" | "national_regulator" | "other">;
  dated_sources: CISSecondarySanctionsExposureRequestDatedSource[];
  risk_question: string;
  decision_stage: "onboarding" | "periodic_review" | "pre_transaction" | "post_alert" | "committee_review" | "other";
  notes?: string;
  requested_output?: "structured_json" | "markdown_summary" | "both";
}

export type CISSecondarySanctionsExposureResponseSourceType = "ofac_sdn_extract" | "eu_consolidated_extract" | "uk_ofsi_extract" | "un_security_council_extract" | "ownership_chain_evidence" | "beneficial_ownership_source" | "bank_correspondent_evidence" | "transit_or_invoice_evidence" | "dual_use_export_evidence" | "customs_data_evidence" | "adverse_media_evidence" | "typology_reference" | "national_regulator_filing" | "user_provided_note" | "other";

export interface CISSecondarySanctionsExposureResponseReadinessNamedValue {
  field: string;
  value: string;
}

/** Additive normalized readiness view for cross-profile human-review routing. Built from existing response fields; does not replace profile-specific fields and does not imply approval, clearance, advice, factual verification, or autonomous decision-making. */
export interface CISSecondarySanctionsExposureResponseReadinessContract {
  profile: string;
  status: string;
  score: number | null;
  routing: CISSecondarySanctionsExposureResponseReadinessNamedValue | null;
  signal: CISSecondarySanctionsExposureResponseReadinessNamedValue | null;
  blocking_gaps: unknown[];
  non_blocking_gaps: unknown[];
  claim_audit: unknown[];
  owner_actions: unknown[];
  watch_next: string[];
  human_review_required: boolean;
  boundary_notice: string;
}

/** Product-grade structured response contract for CIS counterparty secondary-sanctions exposure evidence triage. Supports source-coverage gaps, exposure-dimension routing, FATF / EAG typology references, watch-next indicators, and human-review requirements. It does not provide legal advice, sanctions advice, compliance advice, financial advice, investment advice, insurance advice, trading advice, live retrieval, or factual-truth verification. */
export interface CISSecondarySanctionsExposureResponse {
  triage_recommendation: "not_decision_ready" | "escalate_before_onboarding" | "escalate_before_transaction" | "ready_for_human_review" | "insufficient_information";
  secondary_exposure_signal: "low" | "medium" | "medium_high" | "high" | "unknown";
  /** Heuristic 0-100 score for evidence-pack readiness for human review. This is not approval, clearance, legal advice, sanctions advice, compliance advice, financial advice, investment advice, insurance advice, or trading advice. */
  decision_readiness_score: number;
  decision_readiness_label: "insufficient_information" | "not_decision_ready" | "partial" | "review_ready";
  counterparty: {
    [key: string]: unknown;
  };
  exposure_facets?: string[];
  supplied_sources: CISSecondarySanctionsExposureResponseSourceType[];
  minimum_sources_before_review: CISSecondarySanctionsExposureResponseSourceType[];
  evidence_gaps: string[];
  top_exposure_dimensions?: string[];
  /** Optional mapping to publicly published FATF / EAG / OFAC / EU typology categories the supplied evidence touches. Reference only, not a finding. */
  typology_refs?: Array<{
    framework: "fatf" | "eag" | "ofac" | "eu" | "uk_ofsi" | "national" | "other";
    code?: string;
    label: string;
    source_index?: number;
  }>;
  watch_next: string[];
  human_review_required: boolean;
  not_advice_notice: string;
  limitations?: string[];
  readiness_contract?: CISSecondarySanctionsExposureResponseReadinessContract;
}

/** Product-grade structured request contract for Critical Minerals & Strategic Raw Materials evidence triage (EU Critical Raw Materials Act, EU CSDDD, US Inflation Reduction Act, and export-control compliance). This schema describes caller-supplied mineral commodity, extraction jurisdiction, processing route, counterparty, and decision-stage inputs. It does not enable live retrieval, factual-truth verification, legal advice, compliance advice, sanctions advice, or ESG certification. */
export interface CriticalMineralsDueDiligenceRequest {
  project_name: string;
  commodity: "lithium" | "rare_earth_elements" | "nickel" | "cobalt" | "copper" | "graphite" | "manganese" | "tungsten" | "gallium_germanium" | "other_critical_mineral";
  origin_jurisdiction: string;
  processing_jurisdiction?: string;
  target_market?: "eu" | "us" | "uk" | "japan_korea" | "global" | "domestic";
  decision_question: string;
  decision_stage: "pre_exploration" | "pre_offtake_agreement" | "pre_processing_contract" | "pre_export_shipment" | "pre_investment_decision";
  counterparties?: Array<{
    name: string;
    role: "mine_operator" | "concession_holder" | "refinery_processor" | "trading_intermediary" | "offtake_buyer" | "transport_logistics_carrier" | "government_entity";
    jurisdiction: string;
    state_owned_or_affiliated?: boolean;
    beneficial_owners?: string[];
    sanctions_screening_ref?: string;
  }>;
  supplied_sources: Array<{
    source_type: string;
    title?: string;
    url?: string;
    date?: string;
    issuing_authority?: string;
    verified_by_counsel?: boolean;
    summary?: string;
  }>;
  dated_sources?: Array<{
    source_type: string;
    title?: string;
    url?: string;
    date?: string;
    issuing_authority?: string;
    verified_by_counsel?: boolean;
    summary?: string;
  }>;
  assumptions?: string[];
  blockers?: string[];
}

export interface CriticalMineralsDueDiligenceResponseReadinessNamedValue {
  field: string;
  value: string;
}

/** Additive normalized readiness view for cross-profile human-review routing. */
export interface CriticalMineralsDueDiligenceResponseReadinessContract {
  profile: string;
  status: string;
  score: number | null;
  routing: CriticalMineralsDueDiligenceResponseReadinessNamedValue | null;
  signal: CriticalMineralsDueDiligenceResponseReadinessNamedValue | null;
  blocking_gaps: unknown[];
  non_blocking_gaps: unknown[];
  claim_audit: unknown[];
  owner_actions: unknown[];
  watch_next: string[];
  human_review_required: boolean;
  boundary_notice: string;
}

/** Product-grade structured response contract for Critical Minerals & Strategic Raw Materials evidence triage. Provides deterministic evaluation of origin tracing, export-control flags, beneficiation bottleneck risks, and CSDDD compliance gaps. It does not provide legal advice, sanctions advice, compliance advice, financial advice, ESG certification, live retrieval, or factual-truth verification. */
export interface CriticalMineralsDueDiligenceResponse {
  triage_recommendation: "not_decision_ready" | "escalate_before_offtake" | "escalate_before_shipment" | "escalate_before_investment" | "ready_for_human_review" | "insufficient_information";
  risk_signal: "low" | "medium" | "medium_high" | "high" | "unknown";
  decision_readiness_score: number;
  decision_readiness_label: "insufficient_information" | "not_decision_ready" | "partial" | "review_ready";
  operational_decision: {
    decision: "stop" | "request_evidence" | "require_approval" | "continue";
    reason_code: string;
    blocking_gaps: string[];
    next_permitted_action?: string;
  };
  commodity: string;
  origin_jurisdiction: string;
  processing_jurisdiction?: string;
  target_market?: string;
  traceability_status: "verified" | "partial" | "unverified" | "obfuscated";
  export_control_exposure?: {
    quota_restricted: boolean;
    processing_monopoly_risk?: boolean;
    jurisdiction_risk_flags: string[];
  };
  supplied_sources: string[];
  minimum_sources_before_go: string[];
  evidence_gaps: string[];
  top_risks?: Array<{
    category: string;
    severity: "high" | "medium" | "low";
    description: string;
  }>;
  exposure_layers?: Array<{
    layer: string;
    level: string;
    summary: string;
  }>;
  watch_next: string[];
  human_review_required: boolean;
  not_advice_notice: string;
  readiness_contract?: CriticalMineralsDueDiligenceResponseReadinessContract;
  run_provenance?: {
    contract_version: string;
    input_digest: string;
    schema_uri: string;
  };
}

export interface GulfMaritimeExposureRequestVessel {
  name?: string;
  /** IMO number, if known. Not verified by this service. */
  imo?: string;
  flag?: string;
  vessel_type?: string;
}

export interface GulfMaritimeExposureRequestVoyage {
  chokepoint: "strait_of_hormuz" | "persian_gulf" | "gulf_of_oman" | "bab_el_mandeb" | "red_sea" | "suez_canal" | "other";
  origin?: string;
  destination?: string;
  route_note?: string;
}

export interface GulfMaritimeExposureRequestCounterparty {
  role: "registered_owner" | "beneficial_owner" | "operator" | "charterer" | "manager" | "insurer_or_pi_club" | "flag_registry" | "bunker_supplier" | "other";
  name?: string;
  jurisdiction?: string;
}

export type GulfMaritimeExposureRequestExposureFacet = "iran_oil_exposure" | "russia_oil_price_cap" | "dark_fleet_indicators" | "sts_transfer" | "flag_hopping" | "insurance_or_pi_gap" | "ais_manipulation" | "ownership_or_control" | "dual_use_cargo" | "chokepoint_disruption";

export interface GulfMaritimeExposureRequestDatedSource {
  id: string;
  source_type: GulfMaritimeExposureRequestSourceType;
  title: string;
  date: string;
  url?: string;
  notes?: string;
}

export type GulfMaritimeExposureRequestSourceType = "vessel_registry_extract" | "flag_registry_record" | "pi_insurance_certificate" | "ais_track_record" | "sts_transfer_evidence" | "ownership_or_control_evidence" | "sanctions_list_extract" | "cargo_or_bl_evidence" | "classification_society_record" | "port_state_control_record" | "charterer_kyc_evidence" | "adverse_media_evidence" | "prior_incident_or_detention" | "price_cap_attestation_or_recordkeeping" | "human_review_note" | "user_provided_note" | "other";

/** Product-grade structured request contract for evidence triage of maritime sanctions and chokepoint-disruption exposure for a vessel or voyage transiting the Strait of Hormuz, Persian/Arabian Gulf, Gulf of Oman, Bab-el-Mandeb, or Red Sea. The contract asks whether the supplied evidence is sufficient for allow, escalate-before-fixture, escalate-before-voyage, human-review, or not-decision-ready routing. It does not provide legal, sanctions, compliance, financial, investment, insurance, or trading advice, identity verification, vessel-ownership resolution, live retrieval, or factual-truth verification. */
export interface GulfMaritimeExposureRequest {
  vessel?: GulfMaritimeExposureRequestVessel;
  voyage: GulfMaritimeExposureRequestVoyage;
  /** Cargo under carriage (e.g. crude oil, refined products, LNG, dual-use goods, containers). */
  cargo?: string;
  counterparties?: GulfMaritimeExposureRequestCounterparty[];
  exposure_facets: GulfMaritimeExposureRequestExposureFacet[];
  jurisdictions_in_scope?: Array<"OFAC" | "EU" | "UK_OFSI" | "UN" | "OTHER">;
  decision_stage: "pre_fixture" | "pre_voyage" | "pre_port_call" | "post_alert" | "committee_review" | "other";
  dated_sources: GulfMaritimeExposureRequestDatedSource[];
  risk_question: string;
  notes?: string;
  requested_output?: "structured_json" | "markdown_summary" | "both";
}

export interface GulfMaritimeExposureResponseReadinessNamedValue {
  field: string;
  value: string;
}

/** Additive normalized readiness view for cross-profile human-review routing. Built from existing response fields; does not replace profile-specific fields and does not imply approval, clearance, advice, factual verification, or autonomous decision-making. */
export interface GulfMaritimeExposureResponseReadinessContract {
  profile: string;
  status: string;
  score: number | null;
  routing: GulfMaritimeExposureResponseReadinessNamedValue | null;
  signal: GulfMaritimeExposureResponseReadinessNamedValue | null;
  blocking_gaps: unknown[];
  non_blocking_gaps: unknown[];
  claim_audit: unknown[];
  owner_actions: unknown[];
  watch_next: string[];
  human_review_required: boolean;
  boundary_notice: string;
}

/** Structured response for maritime sanctions and chokepoint-disruption exposure triage. Evidence-sufficiency triage only; always requires human review. Not legal, sanctions, compliance, financial, investment, insurance, or trading advice. */
export interface GulfMaritimeExposureResponse {
  triage_recommendation: "insufficient_information" | "escalate_before_fixture" | "escalate_before_voyage" | "not_decision_ready" | "ready_for_human_review";
  exposure_signal: "low" | "medium" | "medium_high" | "high" | "unknown";
  decision_readiness_score: number;
  decision_readiness_label: "insufficient_information" | "not_decision_ready" | "partial" | "review_ready";
  vessel?: {
    [key: string]: unknown;
  };
  voyage: {
    [key: string]: unknown;
  };
  cargo?: string;
  exposure_facets: string[];
  supplied_sources: string[];
  minimum_sources_before_review: string[];
  evidence_gaps: string[];
  top_exposure_dimensions: string[];
  chokepoint_disruption_watch: string[];
  watch_next: string[];
  human_review_required: true;
  not_advice_notice: string;
  limitations: string[];
  readiness_contract?: GulfMaritimeExposureResponseReadinessContract;
}

export interface MarketEntryReadinessRequestCounterparty {
  role: "supplier" | "distributor" | "dealer" | "customer" | "bank" | "law_firm" | "customs_broker" | "freight_forwarder" | "certification_advisor" | "realtor" | "advertising_agency" | "service_partner" | "government_stakeholder" | "investor" | "other";
  name: string;
  jurisdiction?: string;
  notes?: string;
}

export interface MarketEntryReadinessRequestSuppliedSource {
  id: string;
  source_type: MarketEntryReadinessRequestSourceType;
  title: string;
  date?: string;
  url?: string;
  notes?: string;
}

export type MarketEntryReadinessRequestSourceType = "partner_company_profile" | "product_or_project_description" | "commercial_objective" | "kazakhstan_use_case" | "initial_source_links_or_documents" | "law_firm_opinion" | "counterparty_registry_extract" | "beneficial_ownership_source" | "counterparty_integrity_due_diligence" | "bank_account_and_kyc_onboarding" | "business_substance_evidence" | "authority_to_sign_evidence" | "contract_or_term_sheet_draft" | "tax_accounting_note" | "permanent_establishment_or_tax_residency_assessment" | "currency_control_and_repatriation_note" | "work_permit_and_local_employment_quota_note" | "customs_broker_memo" | "hs_code_classification" | "certification_pathway" | "packing_list_and_incoterms" | "battery_safety_documents" | "freight_forwarder_quote" | "insurance_or_cargo_handling_note" | "landed_cost_model" | "supplier_moq_payment_terms" | "showroom_lease_offer" | "showroom_opex_model" | "outdoor_advertising_quote" | "localized_customer_materials" | "warranty_policy" | "service_partner_confirmation" | "spare_parts_price_list" | "demo_unit_plan" | "test_ride_or_pilot_safety_process" | "trademark_or_brand_protection_filing" | "data_localization_and_privacy_note" | "dealer_interview_notes" | "fleet_customer_validation" | "dealer_margin_model" | "fleet_tco_model" | "financing_or_leasing_partner_note" | "service_sla_draft" | "regional_expansion_assumption_register" | "market_size_source" | "competitor_scan" | "pricing_benchmark" | "customer_interview_notes" | "government_or_akimat_note" | "local_content_or_procurement_localization_note" | "special_economic_zone_eligibility_note" | "bankability_note" | "sdg_or_sustainability_mapping" | "project_timeline" | "risk_register" | "decision_log" | "grid_connection_and_offtake_evidence" | "land_or_site_control_evidence" | "ip_ownership_and_licensing_evidence" | "export_control_classification_note" | "user_provided_note" | "other";

/** Product-grade structured request contract for Kazakhstan market-entry evidence triage. This schema describes caller-supplied company, project, counterparty, source, and decision-stage inputs. It does not enable live retrieval, factual-truth verification, legal advice, compliance advice, customs advice, tax advice, financial advice, investment advice, insurance advice, sanctions advice, or launch authorization. */
export interface MarketEntryReadinessRequest {
  project_name: string;
  partner_or_company: string;
  market: string;
  sector?: "mobility" | "renewable_energy" | "epc" | "infrastructure" | "data_center" | "technology_transfer" | "distribution" | "real_estate_or_land" | "other";
  commercial_objective?: string;
  decision_question: string;
  decision_stage: "concept_review" | "pre_entity_setup" | "pre_signature" | "pre_import" | "pre_certification" | "pre_showroom_lease" | "pre_first_batch_order" | "pre_ad_spend" | "pre_dealer_contract" | "committee_review" | "other";
  counterparties?: MarketEntryReadinessRequestCounterparty[];
  supplied_sources: MarketEntryReadinessRequestSuppliedSource[];
  known_assumptions?: string[];
  known_blockers?: string[];
  requested_output?: "management_summary" | "structured_json" | "both";
}

export interface MarketEntryReadinessResponseEvidenceGap {
  source_type: string;
  evidence_needed: string;
  why_it_matters: string;
  owner: string;
  next_action: string;
  decision_blocked: string;
}

export interface MarketEntryReadinessResponseClaimAuditItem {
  claim: string;
  status: "supported" | "directionally_supported" | "assumption_only" | "unsupported" | "needs_professional_confirmation";
  how_to_use_now: string;
}

export interface MarketEntryReadinessResponseOwnerAction {
  timeframe: "48_hours" | "7_days" | "30_days" | "later";
  owner: string;
  action: string;
  output: string;
}

export interface MarketEntryReadinessResponseReadinessNamedValue {
  field: string;
  value: string;
}

/** Additive normalized readiness view for cross-profile human-review routing. Built from existing response fields; does not replace profile-specific fields and does not imply approval, clearance, advice, factual verification, or autonomous decision-making. */
export interface MarketEntryReadinessResponseReadinessContract {
  profile: string;
  status: string;
  score: number | null;
  routing: MarketEntryReadinessResponseReadinessNamedValue | null;
  signal: MarketEntryReadinessResponseReadinessNamedValue | null;
  blocking_gaps: unknown[];
  non_blocking_gaps: unknown[];
  claim_audit: unknown[];
  owner_actions: unknown[];
  watch_next: string[];
  human_review_required: boolean;
  boundary_notice: string;
}

/** Product-grade structured response contract for Kazakhstan market-entry evidence triage. This schema supports gate decisions, readiness labels, evidence gaps, claim audit, owner actions, watch-next indicators, and human-review requirements. It does not provide legal advice, compliance advice, customs advice, tax advice, financial advice, investment advice, insurance advice, sanctions advice, live retrieval, factual-truth verification, or launch authorization. */
export interface MarketEntryReadinessResponse {
  gate_decision: "proceed_to_validation" | "pause_for_evidence" | "route_to_committee" | "escalate_before_signature" | "not_decision_ready" | "stop";
  readiness_label: "insufficient_information" | "concept_ready" | "validation_ready" | "committee_review_ready" | "launch_commitment_ready";
  human_review_required: boolean;
  summary: string;
  strongest_reason_to_proceed?: string;
  strongest_reason_to_pause?: string;
  confirmed_facts?: string[];
  assumptions?: string[];
  evidence_gaps: MarketEntryReadinessResponseEvidenceGap[];
  claim_audit?: MarketEntryReadinessResponseClaimAuditItem[];
  owner_actions: MarketEntryReadinessResponseOwnerAction[];
  watch_next: string[];
  management_note?: string;
  boundary_notice: string;
  /** Deterministic content-provenance stamp for reproducibility. It is not a signature of authenticity, factuality, clearance, compliance, or authorization. */
  run_provenance?: {
    contract_version: string;
    schema_id: string;
    input_digest: string;
  };
  readiness_contract?: MarketEntryReadinessResponseReadinessContract;
}

export interface MiddleCorridorDealRiskRequestCounterparty {
  role: "shipper" | "forwarder" | "carrier" | "port_agent" | "consignee" | "bank" | "insurer" | "broker" | "customs_broker" | "unknown" | "other";
  name: string;
  jurisdiction?: string;
  notes?: string;
  /** Optional. Sectors the counterparty operates in, drawn from OFAC FAQ 1148 / 1151 named sectors of the Russian Federation economy. A counterparty operating in any non-'other' value carries automatic FFI sanctions-exposure context under EO 14024 as amended by EO 14114. Structural tagging only; not a sanctions determination. */
  specified_sectors?: Array<"technology" | "defense_and_related_materiel" | "construction" | "aerospace" | "manufacturing" | "other">;
  /** Optional. ISO 8601 date of the counterparty's company formation. Drawn from the OFAC FFI advisory red-flag pattern of a newly-formed entity in a transshipment-risk jurisdiction. Structural tagging only; not a sanctions determination. */
  date_of_formation?: string;
}

export interface MiddleCorridorDealRiskRequestDatedSource {
  id: string;
  source_type: MiddleCorridorDealRiskRequestSourceType;
  title: string;
  date: string;
  url?: string;
  notes?: string;
}

export type MiddleCorridorDealRiskRequestSourceType = "port_operator_notice" | "sanctions_list_extract" | "carrier_note" | "counterparty_registry_extract" | "beneficial_ownership_source" | "customs_or_regulatory_source" | "insurance_clause_or_underwriter_note" | "vessel_or_carrier_history" | "rail_capacity_or_border_wait_source" | "contract_or_invoice_extract" | "end_user_or_reexport_evidence" | "source_of_funds_or_wealth_evidence" | "pep_screening_evidence" | "business_substance_evidence" | "user_provided_note" | "other";

/** Product-grade structured request contract for Kazakhstan / Middle Corridor deal-risk evidence triage. This schema describes caller-supplied route, cargo, counterparty, dated-source, and decision-stage inputs. It does not enable live retrieval, factual-truth verification, legal advice, sanctions advice, compliance advice, financial advice, investment advice, insurance advice, or trading advice. */
export interface MiddleCorridorDealRiskRequest {
  /** Route, corridor, or transit path under review. */
  route: string;
  /** Cargo, commodity, goods, or shipment type under review. */
  cargo: string;
  shipment_value?: {
    amount: number;
    currency: "USD" | "EUR" | "GBP" | "KZT" | "CNY" | "TRY" | "AED" | "other";
  };
  counterparties: MiddleCorridorDealRiskRequestCounterparty[];
  dated_sources: MiddleCorridorDealRiskRequestDatedSource[];
  risk_question: string;
  decision_stage: "pre_signature" | "pre_shipment" | "in_transit" | "post_incident" | "committee_review" | "other";
  notes?: string;
  requested_output?: "structured_json" | "markdown_summary" | "both";
}

export interface MiddleCorridorDealRiskResponseCounterparty {
  role: "shipper" | "forwarder" | "carrier" | "port_agent" | "consignee" | "bank" | "insurer" | "broker" | "customs_broker" | "unknown" | "other";
  name: string;
  jurisdiction?: string;
  notes?: string;
  /** Optional. Sectors the counterparty operates in, drawn from OFAC FAQ 1148 / 1151 named sectors of the Russian Federation economy. A counterparty operating in any non-'other' value carries automatic FFI sanctions-exposure context under EO 14024 as amended by EO 14114. Structural tagging only; not a sanctions determination. */
  specified_sectors?: Array<"technology" | "defense_and_related_materiel" | "construction" | "aerospace" | "manufacturing" | "other">;
  /** Optional. ISO 8601 date of the counterparty's company formation. Drawn from the OFAC FFI advisory red-flag pattern of a newly-formed entity in a transshipment-risk jurisdiction. Structural tagging only; not a sanctions determination. */
  date_of_formation?: string;
}

export type MiddleCorridorDealRiskResponseSourceType = "port_operator_notice" | "sanctions_list_extract" | "carrier_note" | "counterparty_registry_extract" | "beneficial_ownership_source" | "customs_or_regulatory_source" | "insurance_clause_or_underwriter_note" | "vessel_or_carrier_history" | "rail_capacity_or_border_wait_source" | "contract_or_invoice_extract" | "end_user_or_reexport_evidence" | "source_of_funds_or_wealth_evidence" | "pep_screening_evidence" | "business_substance_evidence" | "user_provided_note" | "other";

export interface MiddleCorridorDealRiskResponseReadinessNamedValue {
  field: string;
  value: string;
}

/** Additive normalized readiness view for cross-profile human-review routing. Built from existing response fields; does not replace profile-specific fields and does not imply approval, clearance, advice, factual verification, or autonomous decision-making. */
export interface MiddleCorridorDealRiskResponseReadinessContract {
  profile: string;
  status: string;
  score: number | null;
  routing: MiddleCorridorDealRiskResponseReadinessNamedValue | null;
  signal: MiddleCorridorDealRiskResponseReadinessNamedValue | null;
  blocking_gaps: unknown[];
  non_blocking_gaps: unknown[];
  claim_audit: unknown[];
  owner_actions: unknown[];
  watch_next: string[];
  human_review_required: boolean;
  boundary_notice: string;
}

/** Product-grade structured response contract for Kazakhstan / Middle Corridor deal-risk evidence triage. This schema supports source-coverage gaps, escalation routing, watch-next indicators, and human-review requirements. It does not provide legal advice, sanctions advice, compliance advice, financial advice, investment advice, insurance advice, trading advice, live retrieval, or factual-truth verification. */
export interface MiddleCorridorDealRiskResponse {
  triage_recommendation: "not_decision_ready" | "escalate_before_signature" | "escalate_before_shipment" | "ready_for_human_review" | "insufficient_information";
  risk_signal: "low" | "medium" | "medium_high" | "high" | "unknown";
  /** Heuristic 0-100 score for evidence-pack readiness for human review. This is not approval, clearance, legal advice, sanctions advice, compliance advice, financial advice, investment advice, insurance advice, or trading advice. */
  decision_readiness_score: number;
  decision_readiness_label: "insufficient_information" | "not_decision_ready" | "partial" | "review_ready";
  /** Observe-only structural lint of cited source-URL well-formedness. Present only when at least one supplied source carries a malformed or placeholder URL. Structural check only: it does not fetch URLs, verify that a page exists, perform live retrieval, or verify factual content. It does not change the triage recommendation, risk signal, operational decision, or evidence gaps. */
  link_integrity?: {
    checked: number;
    well_formed?: number;
    illustrative?: number;
    flagged: Array<{
      source_id?: string;
      source_type?: string;
      url: string;
      reason: string;
    }>;
  };
  /** Logistics/ops-facing booking decision derived from the decision-readiness score, risk signal, triage recommendation, and decision stage. Triage routing only; not clearance, approval, a sanctions determination, or any legal, sanctions, compliance, financial, investment, insurance, or trading advice. It never issues a hard reject (a compliance/legal call) and stops at hold or escalate. Human review is required before any commercial action. */
  operational_decision?: {
    decision: "proceed" | "proceed_with_conditions" | "hold" | "escalate";
    applies_to: string;
    rationale: string;
  };
  route?: string;
  cargo?: string;
  shipment_value?: {
    amount: number;
    currency: "USD" | "EUR" | "GBP" | "KZT" | "CNY" | "TRY" | "AED" | "other";
  };
  counterparties?: MiddleCorridorDealRiskResponseCounterparty[];
  supplied_sources: MiddleCorridorDealRiskResponseSourceType[];
  minimum_sources_before_go: MiddleCorridorDealRiskResponseSourceType[];
  evidence_gaps: string[];
  top_risks?: string[];
  /** Risk picture decomposed into the two layers a practitioner separates: home-jurisdiction legal / documentation posture (not assessed by this product) versus foreign / secondary-sanctions exposure. Structural decomposition only; not a legal or sanctions determination. */
  exposure_layers?: {
    domestic_legal_layer?: string[];
    foreign_sanctions_exposure_layer?: string[];
  };
  /** Deceptive-shipping-practice (DSP) verification checklist surfaced for the maritime leg when vessel / carrier history is not yet supplied. An evidence-gap checklist routed to human review (drawn from OFAC maritime guidance); not vessel adjudication, AIS analysis, live retrieval, or insurance advice. */
  vessel_due_diligence_indicators?: string[];
  /** End-use / end-user verification checklist surfaced when end-user or no-re-export evidence is not yet supplied. An evidence-gap checklist routed to human review (drawn from EU Sanctions Helpdesk and US end-user diversion red flags); not an end-use determination, sanctions determination, live retrieval, or legal advice. Does not affect the decision-readiness score. */
  reexport_control_indicators?: string[];
  /** Source-of-funds / source-of-wealth verification checklist surfaced when source-of-funds-or-wealth evidence is not yet supplied. An evidence-gap checklist routed to human review (drawn from FATF Recommendation 10 EDD guidance); not a financial determination, AML clearance, live retrieval, or financial advice. Does not affect the decision-readiness score. */
  source_of_funds_indicators?: string[];
  /** Politically-exposed-person (PEP) screening checklist surfaced when PEP-screening evidence is not yet supplied. An evidence-gap checklist routed to human review (drawn from FATF Recommendations 12 and 22); not a PEP determination, a political-exposure judgment, live retrieval, or legal advice. Does not affect the decision-readiness score. */
  pep_screening_indicators?: string[];
  /** Front-company / business-substance checklist surfaced when business-substance evidence is not yet supplied. An evidence-gap checklist routed to human review (drawn from EU Sanctions Helpdesk counterparty red flags: recently established or no business background, little or no web presence, shared addresses, line-of-business mismatch, contact only via broad power of attorney); not a shell-company determination, an ownership determination, live retrieval, or legal advice. Does not affect the decision-readiness score. */
  front_company_indicators?: string[];
  /** Standing route-screening checklist of Middle Corridor connections that carry elevated sanctions-program exposure: Iran-transit legs and Russia Northern Corridor overlaps (OFAC Iran and Russia programs), sanctioned Caspian operators, and onward connections into a sanctions-relevant jurisdiction. Presence-flagging routed to human review; not a sanctions determination, live screening, or legal advice. */
  route_sanctions_exposure_indicators?: string[];
  /** Corridor segments named in the declared route text that match a sanctions-exposed connection on the screening checklist. Case-insensitive substring presence-flagging on the route string only, routed to human review; not a sanctions determination or live screening. Does not affect the decision-readiness score. */
  route_sanctions_matched_segments?: string[];
  /** Standing customs-regime review checklist for the route: permitting clarity, and harmonized digital-customs coverage (eTIR; adopted by Organization of Turkic States members) versus unharmonized national permitting that remains a recurring barrier to private-sector corridor use. Evidence-gap prompts routed to human review; not customs, legal, or compliance advice. Does not affect the decision-readiness score. */
  customs_harmonization_indicators?: string[];
  watch_next: string[];
  human_review_required: boolean;
  not_advice_notice: string;
  limitations?: string[];
  /** Outward-facing reframe of the evidence-gap picture for the party that must PRESENT a due-diligence dossier to a bank, insurer, or counterparty under enhanced due diligence, rather than the internal analyst deciding whether to escalate. Derived from the required-before-go contract and supplied sources. Dossier-completeness only; not clearance, approval, a sanctions determination, or compliance advice. */
  counterparty_readiness?: {
    status: "insufficient_information" | "incomplete" | "partial" | "complete_for_review";
    required_total: number;
    supplied_count: number;
    missing_count: number;
    outstanding_documents: MiddleCorridorDealRiskResponseSourceType[];
    /** Per-required-document ledger mirroring the EDD chain-of-custody practice of tracking each item with the date it was received. One entry per required-before-go source type. date_received is the earliest supplied dated source of that type, when present. Status tracking only; not verification of the document's contents or authenticity. */
    document_ledger?: Array<{
      source_type: MiddleCorridorDealRiskResponseSourceType;
      status: "received" | "missing";
      date_received?: string;
    }>;
    presentable_note: string;
  };
  /** Deterministic content-provenance stamp: which contract version and response schema produced this output, plus a digest of the exact request input. Lets a downstream reviewer (compliance committee, bank, auditor) confirm the artifact is reproducible from a named input and ruleset. Reproducibility / traceability only; not a signature of authenticity (that is the A2A / JWS transport layer, ADR 0017), and not a factuality, clearance, or compliance attestation. */
  run_provenance?: {
    /** Version of the agenda-intelligence package / ruleset that produced this response. */
    contract_version: string;
    /** The $id of the response schema this output conforms to. */
    schema_id: string;
    /** sha256 of the canonicalized request JSON (UTF-8, keys sorted, no insignificant whitespace). Same input + same contract_version reproduces the same digest. */
    input_digest: string;
  };
  readiness_contract?: MiddleCorridorDealRiskResponseReadinessContract;
}

export interface PreActionCheckRequestActor {
  id: string;
  type: "ai_agent" | "automation" | "api_client" | "human_delegated_agent" | "unknown" | "other";
  operator?: string;
}

export interface PreActionCheckRequestTarget {
  id: string;
  type: string;
}

export interface PreActionCheckRequestClaim {
  claim_id: string;
  claim: string;
  claim_type?: "regulatory_change" | "regulatory_gap" | "sanctions_event" | "geopolitical_event" | "market_event" | "industry_response" | "corporate_disclosure" | "capability_claim";
  evidence_ids?: string[];
  support_level: "direct" | "partial" | "weak" | "unsupported";
  uncertainty?: string;
  risk_if_wrong?: string;
  supporting_quotes?: Array<{
    evidence_id: string;
    quote: string;
  }>;
}

export interface PreActionCheckRequestEvidenceItem {
  evidence_id: string;
  name?: string;
  url?: string;
  source_type: string;
  freshness?: string;
  supports?: string[];
  limits?: string[];
}

export interface PreActionCheckRequestPolicyContext {
  profile?: "default" | "agentic_interaction_trust";
  checks?: Array<{
    check_id: string;
    status: "passed" | "needs_evidence" | "failed";
    evidence_gap?: string;
  }>;
}

export interface PreActionCheckRequestApproval {
  status: "not_requested" | "approved" | "rejected";
  /** Opaque caller-held reference to an external approval record. */
  reference?: string;
}

/** Caller-supplied action context and claim evidence for deterministic pre-action routing. The check can continue, request evidence, require human approval, or stop. It does not authenticate the actor, verify factual truth, enforce the decision, or authorize the action. */
export interface PreActionCheckRequest {
  /** Caller-generated correlation identifier. Resubmit the same run_id after adding evidence or approval. */
  run_id: string;
  actor: PreActionCheckRequestActor;
  requested_action: string;
  target: PreActionCheckRequestTarget;
  risk_tier: "low" | "medium" | "high" | "critical";
  claims: PreActionCheckRequestClaim[];
  evidence: PreActionCheckRequestEvidenceItem[];
  unsupported_claims?: string[];
  policy_context?: PreActionCheckRequestPolicyContext;
  approval?: PreActionCheckRequestApproval;
}

/** Deterministic routing result for a caller-controlled action boundary. The response reports readiness; the caller remains responsible for enforcement, authentication, authorization, approval storage, and the action itself. */
export interface PreActionCheckResponse {
  decision_id: string;
  run_id: string;
  policy_version: "pre-action-check.v1";
  decision: "continue" | "request_evidence" | "require_approval" | "stop";
  reason_code: "evidence_ready" | "evidence_gaps" | "unsafe_claims" | "policy_check_failed" | "approval_required_for_risk" | "approval_rejected";
  blocking_gaps: string[];
  evidence_requests: string[];
  approval_required: boolean;
  human_review_required: boolean;
  verification: {
    [key: string]: unknown;
  };
  policy_checks?: Array<{
    check_id: string;
    status: "passed" | "needs_evidence" | "failed";
    evidence_gap?: string;
  }>;
  /** Present on decision_check. unavailable fails the signed Gate path closed. */
  receipt_status?: "signed" | "unavailable";
  /** Short-lived readiness receipt attached by decision_check. The legacy pre_action_check response omits it. */
  receipt?: null | {
    format: "agenda-readiness-receipt+jws";
    token: string;
    receipt_id: string;
    issued_at: string;
    expires_at: string;
    request_hash: string;
    action_hash: string;
    verification_tool: "decision_verify";
  };
  not_authorization_notice: string;
  limitations: string[];
}
