#!/usr/bin/env python3
"""
Agent Factory: Dynamically create new vertical agent profiles.

Scaffolds a proposed vertical profile for later implementation and review. It generates:
1. A new capability profile in data/skills/
2. Boilerplate schemas
3. An entry in agent-manifest.json

Usage:
    python3 scripts/agent-factory.py "Real Estate Due Diligence" --id "real_estate_dd"
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description="Scaffold a new vertical agent profile.")
    parser.add_argument("name", help='Human readable name, e.g. "ESG Compliance Auditor"')
    parser.add_argument("--id", required=True, help='Profile ID, e.g. "esg_compliance"')
    args = parser.parse_args()

    profile_id = args.id.lower().replace("-", "_")
    profile_dir = ROOT / "src" / "agenda_intelligence" / "data" / "skills" / profile_id
    profile_dir.mkdir(parents=True, exist_ok=True)

    # 1. Scaffold SKILL.md
    skill_content = f"""---
name: {args.name}
id: {profile_id}
version: 1.0.0
---
# {args.name}
This profile is dynamically generated by the Agent Factory.
It evaluates {args.name} checklists for evidence readiness.
"""
    (profile_dir / "SKILL.md").write_text(skill_content)

    # 2. Update agent-manifest.json
    manifest_path = ROOT / "agent-manifest.json"
    if manifest_path.exists():
        with open(manifest_path, "r") as f:
            manifest = json.load(f)

        # Add tool to manifest
        new_tool = {
            "name": profile_id,
            "description": f"Proposed evidence-packet checker for {args.name}; implementation required.",
            "inputSchema": {
                "type": "object",
                "properties": {f"{profile_id}_request": {"type": "object", "description": "Payload for " + args.name}},
            },
        }

        if "mcp_tools" in manifest:
            # Check if it exists
            if not any(t["name"] == profile_id for t in manifest["mcp_tools"]):
                manifest["mcp_tools"].append(new_tool)
                with open(manifest_path, "w") as f:
                    json.dump(manifest, f, indent=2)
                print(f"✅ Added {profile_id} to agent-manifest.json")
            else:
                print(f"⚠️ Tool {profile_id} already exists in manifest.")

    print(f"Generated proposed profile scaffold: {args.name} ({profile_id})")
    print("Inactive until schemas, implementation, contract tests, review, and manifest validation are complete.")


if __name__ == "__main__":
    main()
